In [19]:
def num_veces(search_string, string):
    array_string = string.split(" ")
    cuenta = 0
    for sub_string in array_string:
        if sub_string == search_string:
            cuenta += 1
    return cuenta


def array_palabras(corpus, vocabulario):
    diccionario = {word: [0,[]] for word in vocabulario}
    for id_documento in range(len(corpus)):
        for word in vocabulario:
            if num_veces(word, corpus[id_documento]) > 0:
                diccionario[word][1].append(id_documento+1)
            diccionario[word][0] = len(diccionario[word][1])
    return diccionario

def palabra_en_doc(corpus, palabra):
    lista = np.zeros(len(corpus), dtype=int) 
    for id_documento in range(len(corpus)):
        lista[id_documento] = num_veces(palabra, corpus[id_documento])
    return lista

terminos = [
    "carro",
    "compra",
    "industrial",
    "libro",
    "máquina",
    "mecánica",
    "nuevo",
    "usado",
    "venta",
]

documentos = [
    "venta carro usado",
    "venta libro usado venta libro nuevo",
    "compra máquina industrial máquina mecánica",
    "máquina venta usado",
    "libro máquina industrial nuevo"
]

array_palabras(documentos, terminos)

{'carro': [1, [1]],
 'compra': [1, [3]],
 'industrial': [2, [3, 5]],
 'libro': [2, [2, 5]],
 'máquina': [3, [3, 4, 5]],
 'mecánica': [1, [3]],
 'nuevo': [2, [2, 5]],
 'usado': [3, [1, 2, 4]],
 'venta': [3, [1, 2, 4]]}

In [16]:
np.zeros((1, len([1,2])))

array([[0., 0.]])

In [12]:
import numpy as np

In [ ]:
#def tf():
for word in terminos:
    print(word, palabra_en_doc(documentos, word))


carro [1 0 0 0 0]
compra [0 0 1 0 0]
industrial [0 0 1 0 1]
libro [0 2 0 0 1]
máquina [0 0 2 1 1]
mecánica [0 0 1 0 0]
nuevo [0 1 0 0 1]
usado [1 1 0 1 0]
venta [1 2 0 1 0]


In [ ]:
def idf(documentos, palabra):
    N = len(documentos)
    for documento in documentos:
        

In [ ]:
tf_idf = np.zeros((len(terminos), len(documentos)))
for word in terminos:

    tf = np.log10(1 + palabra_en_doc(documentos, word))

    
    
    
    print(tf_idf)
    #idf = np.log10(1 + palab)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0.

In [ ]:
def matriz_tf_idf():
    